### ISSUE TITLE
Key error: id 

### ISSUE THREAD

**Issue by tabindakhan** [TheComeUpCode/SpotifyGeneratePlaylist#30]
I have tried adding new OAuth token from Spotify but  I am still getting this error.
[youtube] 4vPgoVg-ikU: Downloading webpage
Traceback (most recent call last):
  File "C:/Users/Tabinda Khan/PycharmProjects/automatespotify/venv/create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:/Users/Tabinda Khan/PycharmProjects/automatespotify/venv/create_playlist.py", line 127, in add_song_to_playlist
    playlist_id = self.create_playlist()
  File "C:/Users/Tabinda Khan/PycharmProjects/automatespotify/venv/create_playlist.py", line 94, in create_playlist
    return response_json["id"]
KeyError: 'id'

**Comment by jing486** [comment]
I solved this issue by regetting a new OAuth token from Spotify and clicked on all options when it was asking what access you'd like to have

**Comment by tabindakhan** [comment]
Hey I also tried by checking all the boxes and it does make the playlist in my Spotify but the list remains empty and I get Response exception 400 error

**Comment by jeremywoods** [comment]
I'm experiencing this issue as well. I've tried checking all the boxes and that does not work. Any help would be much appreciated.

**Comment by tabindakhan** [comment]
I am still not able to identify the issue myself...

**Comment by CingedBrain** [comment]
Oh my, I have realized I posted a comment on a closed issue previously. I have this exact same issue and I have entered the new token with all the boxes checked. However, still no success. Please let us know if there's a solution. Thank you.

**Comment by aditmodhvadia** [comment]
It will be great if you can post a snapshot of the error with the message and double-check by generating a new token with all the necessary permissions from Spotify.

**Comment by CingedBrain** [comment]
@aditmodhvadia Hey, thanks for the reply. I have been able to resolve the issue stated by me above. However, now there's another issue where there is a playlist being created in Spotify but it is unable to add songs to the playlist. I have posted all the details including the code  in an issue under "Keyerror: Spotify won't work" in the closed issue section.

**Comment by danieltien13** [comment]
youtube_dl is not publishing Artist nor Track names, which is causing the 400 error: https://www.reddit.com/r/youtubedl/comments/hyys57/youtube_dl_not_returning_artist_or_song_name/
