### ISSUE TITLE
exceptions.ResponseException: Response gave status code 400

### ISSUE THREAD

**Issue by paulkasidit** [TheComeUpCode/SpotifyGeneratePlaylist#32]
Hi guys, 

Anybody having this issue when running the program? It shows this error code. 

Traceback (most recent call last):
  File "create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "create_playlist.py", line 146, in add_song_to_playlist
    raise ResponseException(response.status_code)
**exceptions.ResponseException: Response gave status code 400**

A playlist was created in my Spotify, but no videos/songs were imported.

Anybody found a solution to this?

**Comment by aditmodhvadia** [comment]
Hey, it will of great help if you could post a snapshot of the code at the line mentioned in the error above with a few extra lines before and after it.

Also, ensure that your Spotify token has enough permission to add songs to playlists.

**Comment by PauliusBaronas** [comment]
I gave the same issue:

Traceback (most recent call last):
  File "C:\Users\bigpa\OneDrive\spitify project\create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:\Users\bigpa\OneDrive\spitify project\create_playlist.py", line 146, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 400

**Comment by danieltien13** [comment]
It's because youtube_dl is not publishing Artist nor Track names so the all_song_info dict is empty: https://www.reddit.com/r/youtubedl/comments/hyys57/youtube_dl_not_returning_artist_or_song_name/

**Comment by divergentideas** [comment]
> It's because youtube_dl is not publishing Artist nor Track names so the all_song_info dict is empty: https://www.reddit.com/r/youtubedl/comments/hyys57/youtube_dl_not_returning_artist_or_song_name/

Has anyone figured out a workaround? Tried using the solution in the above reddit post, but I got "None" for Artist and Track name.
