### ISSUE TITLE
been trying for hours

### ISSUE THREAD

**Issue by realkdc** [TheComeUpCode/SpotifyGeneratePlaylist#40]
very new to all of this but I was able to get the bot running but now I'm facing this issue and keep getting this code.

[youtube] IEwMrTSqlAc: Downloading webpage
[youtube] IEwMrTSqlAc: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: IEwMrTSqlAc: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1840, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: IEwMrTSqlAc: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "create_playlist.py", line 120, in add_song_to_playlist
    self.get_liked_videos()
  File "create_playlist.py", line 56, in get_liked_videos
    video = youtube_dl.YoutubeDL({}).extract_info(
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/Users/drippo/Desktop/SpotifyGeneratePlaylist-master/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: IEwMrTSqlAc: YouTube said: Unable to extract video data

**Comment by realkdc** [comment]
@TheComeUpCode
