### ISSUE TITLE
ResponseException code 400

### ISSUE THREAD

**Issue by ATB147** [TheComeUpCode/SpotifyGeneratePlaylist#6]
Hi!
First of all, thanks for providing this code!!
I'm very new to this kind of coding, so the solution to my problem may be very simple. After setting up the YouTube OAuth and running the code, my terminal outputs that I'm successfully downloading the correct info from YT, but then I get the following error:

Traceback (most recent call last):
  File "create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "create_playlist.py", line 146, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 400

Can anyone help me figure this out? I did see that the new Spotify playlist was successfully created, but no songs were added to it. I'll edit this post if any more info is needed to diagnose this problem!

**Comment by pariharvivek92** [comment]
same error did you get solve that problem?

**Comment by pariharvivek92** [comment]
hey did you get the solution to this error?

**Comment by Luiz6ustav0** [comment]
Response code 400 is a bad request status code. I'll get into the problem later today if it's not solved but for now I can recommend you check how the api request is being made and see if there's anything invalid. Go to spotify's api documentation and see if the code is building the request correctly.

**Comment by prettybakedcake** [comment]
Got the same error response, playlist gets created on Spotify but doesn't get filled

**Comment by SheebanWasi** [comment]
Same error did you got the answer?

Kinda help mate.

@ATB147 @Luiz6ustav0

**Comment by ryosukenakagiri** [comment]
I got the same error. Please someone help!

**Comment by Igorrubbo** [comment]
I got the same error and after searching the error I found this: "[Your client may be trying to send a file that’s too big](https://airbrake.io/blog/http-errors/400-bad-request)". Since my liked playlist on my main youtube has plenty of videos I decided to try with an alternate youtube account. I liked only two songs and tried the program. It worked, I successfully created a spotify playlist with both songs in it.

But I still get a error message, which is the following:

Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 146, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 201

I'm a noob when it comes to programming and I'm not really sure if this is an error because google tells me that "Responde gave status code 201" is just a message telling me that "[The request has been fulfilled and has resulted in one or more new resources being created](https://httpstatuses.com/201)".
But, if this is not an error, why is it in red?

**Comment by pariharvivek92** [comment]
> I got the same error and after searching the error I found this: "[Your client may be trying to send a file that’s too big](https://airbrake.io/blog/http-errors/400-bad-request)". Since my liked playlist on my main youtube has plenty of videos I decided to try with an alternate youtube account. I liked only two songs and tried the program. It worked, I successfully created a spotify playlist with both songs in it.
> 
> But I still get a error message, which is the following:
> 
> Traceback (most recent call last):
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in
> cp.add_song_to_playlist()
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 146, in add_song_to_playlist
> raise ResponseException(response.status_code)
> exceptions.ResponseException: Response gave status code 201
> 
> I'm a noob when it comes to programming and I'm not really sure if this is an error because google tells me that "Responde gave status code 201" is just a message telling me that "[The request has been fulfilled and has resulted in one or more new resources being created](https://httpstatuses.com/201)".
> But, if this is not an error, why is it in red?

Help to all , could you please listed down the step to get Google OAuth json file

**Comment by Igorrubbo** [comment]
I opened the following website: https://console.developers.google.com/
Selected the credentials tab > clicked on the + Create Credentials button > OAuth Client ID > Select Desktop Web app > Create > Click on the download button. After downloading it you need to put the file on the directory of the SpotifyGeneratePlaylist program. In my case it is located inside C:\Users\Admin\PycharmProjects

Credentials tab:
![Screenshot_2](https://user-images.githubusercontent.com/53878194/82827910-5cec0780-9e86-11ea-84db-b5a187e436bc.png)

Creating the Oauth authenticator:
![Screenshot_3](https://user-images.githubusercontent.com/53878194/82827915-5f4e6180-9e86-11ea-99f3-92b777202bd4.png)

Downloading the json file:
![Screenshot_4](https://user-images.githubusercontent.com/53878194/82827919-61182500-9e86-11ea-97bf-ab90e841139f.png)

**Comment by pariharvivek92** [comment]
> I opened the following website: https://console.developers.google.com/
> Selected the credentials tab > clicked on the + Create Credentials button > OAuth Client ID > Select Desktop Web app > Create > Click on the download button. After downloading it you need to put the file on the directory of the SpotifyGeneratePlaylist program. In my case it is located inside C:\Users\Admin\PycharmProjects
> 
> **Credentials tab:**
> ![Screenshot_2](https://user-images.githubusercontent.com/53878194/82827910-5cec0780-9e86-11ea-84db-b5a187e436bc.png)
> 
> **Creating the Oauth authenticator:**
> ![Screenshot_3](https://user-images.githubusercontent.com/53878194/82827915-5f4e6180-9e86-11ea-99f3-92b777202bd4.png)
> 
> **Downloading the json file:**
> ![Screenshot_4](https://user-images.githubusercontent.com/53878194/82827919-61182500-9e86-11ea-97bf-ab90e841139f.png)

Thanks bro for sharing with us🙂

**Comment by clarecui** [comment]
Going back to the original problem (which I am also running into), the issue is that the video in the `get_liked_videos` method doesn't have the "track" and "artist" keys after retrieving the video info using youtube-dl. I'm on Windows 10 and have the latest version of youtube-dl btw. If anyone has any guidance, much appreciated.

**Comment by KaranRajPradhan** [comment]
Facing same issue: 

Traceback (most recent call last):
  File "create_playlist.py", line 156, in <module>
    cp.add_song_to_playlist()
  File "create_playlist.py", line 148, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 400

**Comment by paulkasidit** [comment]
Hi, has anybody found a solution to this? Still stuck on this. Thank You.
