### ISSUE TITLE
how to run  the code someone help

### ISSUE THREAD

**Issue by prithvi2226** [TheComeUpCode/SpotifyGeneratePlaylist#7]
cannot import name 'spotify_token' from 'secrets'
STUCK HERE
TRIED DOING WITH SPOTIPY(NO LUCK )
CANNOT FIND THE USER ID PRIOR TO THE TOKEN!!
HELP!!!!!!

**Comment by Luiz6ustav0** [comment]
Hi, did you make sure your imports are correct? Did you use 'git clone' to get the exact code from this repo?
The line of imports referring to that should be `from secrets import spotify_token, spotify_user_id`, besides that you should make sure that your secrets.py file contains only 
`spotify_token = ""
spotify_user_id = ""`
Make sure to check these things.

**Comment by prithvi2226** [comment]
okay ill try that

**Comment by prithvi2226** [comment]
Error 400: invalid_request
Missing required parameter: client_id

**Comment by prithvi2226** [comment]
ha thanks a lot! but now how would i get my client_id,client_secrets and token for my youtube API??

**Comment by prithvi2226** [comment]
ha thanks a lot!! but what kind of application is this?? application type?? is it android or web application??

**Comment by prithvi2226** [comment]
Error 400: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient

**Comment by prithvi2226** [comment]
help!!!!!!!!!!!

**Comment by Luiz6ustav0** [comment]
How did you set up your auth token credentials with the youtube data api? I checked it out and saw that several things have changed from the video. You should search for the youtube data api and set up a project do be able to generate the auth token. After that you'll be able to download the client id, user secret and the other things needed for the client_secret.json file.

Also, note that you should select that the api is going to be used by an windows/CLI program for it to work.

**Comment by Igorrubbo** [comment]
> Error 400: redirect_uri_mismatch
> The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient

I had the same problem and solved it by creating another OAuth 2.0 ID but selecting Other when it asks for type of app, a seem in the following picture (although it is in portuguese the arrow points to where "other" would be)
![Screenshot_1](https://user-images.githubusercontent.com/53878194/80636646-2f9d6c80-8a34-11ea-9c29-093f78ac18fe.png)

**Comment by Igorrubbo** [comment]
After that I was allowed to get the authorization but got stuck in the following problem:

Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 127, in add_song_to_playlist
    playlist_id = self.create_playlist()
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 94, in create_playlist
    return response_json["id"]
KeyError: 'id'

I have the secrets.py file filled with the spotify token and my spotify user id. It was hard to find the spotify user id but I found it on the "Set Device Password" part of my Account settings. It show after "Your device username is:".
I tried doing the process again with a new spotify token but I still doesn't work. Can someone help me with this?

**Comment by Luiz6ustav0** [comment]
I haven't been able to reproduce your error but as far as I could imagine by looking at the code, your problem is related to what's returned from the request to the spotify api,you might be getting nothing back or accessing the data within the file wrong. So here are a few things you might check to troubleshoot:
- Make the request in your browser with the data you have(for the header etc) and see if something is returned
- If nothing is returned there's a problem with the way the request is being made, if the data comes theres something wrong with the way the json file is being read, maybe the right way might be something like response_json[0]['id'] instead of response_json['id'], but you'll find that out only by looking at the file or reading the api docs.

**Comment by prithvi2226** [comment]
`[youtube] GS2ZKw3G9-w: Downloading webpage
[youtube] 73-k1aWbhN8: Downloading webpage
[youtube] 7Roztpt7lOs: Downloading webpage
[youtube] SN3nmNBiJ6w: Downloading webpage
[youtube] 8DvywoWv6fI: Downloading webpage
Traceback (most recent call last):
  File "youtube_to_spotify.py", line 148, in <module>
    cp.add_song_to_playlist()
  File "youtube_to_spotify.py", line 126, in add_song_to_playlist
    playlist_id = self.create_playlist()
  File "youtube_to_spotify.py", line 93, in create_playlist
    return response_json["id"]
KeyError: 'id'`

**Comment by prithvi2226** [comment]
> After that I was allowed to get the authorization but got stuck in the following problem:
> 
> Traceback (most recent call last):
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in
> cp.add_song_to_playlist()
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 127, in add_song_to_playlist
> playlist_id = self.create_playlist()
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 94, in create_playlist
> return response_json["id"]
> KeyError: 'id'
> 
> I have the secrets.py file filled with the spotify token and my spotify user id. It was hard to find the spotify user id but I found it on the "Set Device Password" part of my Account settings. It show after "Your device username is:".
> I tried doing the process again with a new spotify token but I still doesn't work. Can someone help me with this?

buddy you got the answer??

**Comment by Igorrubbo** [comment]
Nope, still trying to figure it out. I confirmed that I was using the right user id, tried to make the change to response_json mentioned by Luiz but I still can't make the program work. The user id is found on the "Set Device Password" tab on your profile page.
I didn't try "Make the request in your browser with the data you have(for the header etc) and see if something is returned" because I didn't understand what this is. I was trying to figure it out

**Comment by prithvi2226** [comment]
same! but whats the deal with the spotify user id??isnt it supposed to be the one you use to log in??

**Comment by Igorrubbo** [comment]
I just now realized that above the code of line 94, the one with the id error, there is a comment saying that the id is actually the playlist id and not the user id.
I have a few theories for why this isn't working:
- The program is not creating the playlist, therefore, it isn't creating a playlist id and, because of that, the program can't continue
- id is not defined anywhere so the program doesn't know what to do with return response_json["id"], as seen in line 94, the one with the error

**Comment by Igorrubbo** [comment]
> I haven't been able to reproduce your error but as far as I could imagine by looking at the code, your problem is related to what's returned from the request to the spotify api,you might be getting nothing back or accessing the data within the file wrong. So here are a few things you might check to troubleshoot:
> 
> * Make the request in your browser with the data you have(for the header etc) and see if something is returned
> * If nothing is returned there's a problem with the way the request is being made, if the data comes theres something wrong with the way the json file is being read, maybe the right way might be something like response_json[0]['id'] instead of response_json['id'], but you'll find that out only by looking at the file or reading the api docs.

I looked at the api docs and found out that the playlist id is given as a json file. How could I access the file? The json program that I have access to is the one related to youtube and this one seems to be related to spotify. It seems to me that I can't access the spotify json.
By the way, I'm using the same code as given by The Come Up.
Desde já agradeço pela ajuda, man!

**Comment by Igorrubbo** [comment]
I was able to fix the problem! The solution was In the page that you get the OAuth token. You have to select the boxes when making the token. I wasn't selecting any and the program probaly wasn't getting the id becaues it wasn't allowed to
![Screenshot_2](https://user-images.githubusercontent.com/53878194/80752298-a5233e80-8b01-11ea-8806-0086b9f312e7.png)

**Comment by Igorrubbo** [comment]
But... I new error showed up. I'll stop for now and just come back at the problem tomorrow. Here is the error:

Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in <module>
    cp.add_song_to_playlist()
  File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 146, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 400

**Comment by Luiz6ustav0** [comment]
> I was able to fix the problem! The solution was In the page that you get the OAuth token. You have to select the boxes when making the token. I wasn't selecting any and the program probaly wasn't getting the id becaues it wasn't allowed to
> ![Screenshot_2](https://user-images.githubusercontent.com/53878194/80752298-a5233e80-8b01-11ea-8806-0086b9f312e7.png)

Would you be kind enough to send the link to the dashboard where you generated your OAuth token? I got my client id and secret in a different way and I haven't been able to find these permissions.

**Comment by Luiz6ustav0** [comment]
> But... I new error showed up, which probably has something to do with the exceptions.py file. I'll try to fix it tomorrow. I'm tired. Here is the error:
> 
> Traceback (most recent call last):
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in
> cp.add_song_to_playlist()
> File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 146, in add_song_to_playlist
> raise ResponseException(response.status_code)
> exceptions.ResponseException: Response gave status code 400

Status code 400 stands for a bad request, this means that the server believes there's something wrong in the client side(such as syntax errors) and is not going to process that request until it is modified. The post method used with the request is probably with one of the parameters wrong or something related to that, I believe.

And for clarification purposes, @Igorrubbo and @prithvi2226 , it's probably better if we close this issue and open new ones to specific erros instead of making this long thread, just a suggestion.
If you agree you may close this issue and reference it in the new issue you open for the new error.

**Comment by Igorrubbo** [comment]
> > I was able to fix the problem! The solution was In the page that you get the OAuth token. You have to select the boxes when making the token. I wasn't selecting any and the program probaly wasn't getting the id becaues it wasn't allowed to
> 
> Would you be kind enough to send the link to the dashboard where you generated your OAuth token? I got my client id and secret in a different way and I haven't been able to find these permissions.

I got the link at the front page of this project the link is the following [Get OAuth](https://developer.spotify.com/console/post-playlists/)

**Comment by Igorrubbo** [comment]
> > But... I new error showed up, which probably has something to do with the exceptions.py file. I'll try to fix it tomorrow. I'm tired. Here is the error:
> > Traceback (most recent call last):
> > File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 154, in
> > cp.add_song_to_playlist()
> > File "C:/Users/Admin/PycharmProjects/Pratica/create_playlist.py", line 146, in add_song_to_playlist
> > raise ResponseException(response.status_code)
> > exceptions.ResponseException: Response gave status code 400
> 
> Status code 400 stands for a bad request, this means that the server believes there's something wrong in the client side(such as syntax errors) and is not going to process that request until it is modified. The post method used with the request is probably with one of the parameters wrong or something related to that, I believe.
> 
> And for clarification purposes, @Igorrubbo and @prithvi2226 , it's probably better if we close this issue and open new ones to specific erros instead of making this long thread, just a suggestion.
> If you agree you may close this issue and reference it in the new issue you open for the new error.

Understood! I'll look into it tomorrow! Obrigado, irmão!

Of course how would you suggest us to do it? Just post my last question in a new thread? I'm new to GitHub, that's why I ask

**Comment by Luiz6ustav0** [comment]
Por nada! haha

Yeah, it's better to have issues for specific problems so it's easier to find them later if someone needs etc.

**Comment by prithvi2226** [comment]
aight

**Comment by prithvi2226** [comment]
BUDDYYYYY CODE RAN!!!!!!!!!!!!!

**Comment by prithvi2226** [comment]
C:\Users\Sheeba\Downloads\spotify>python youtube_to_spotify.py
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=736647324931-8acrs87cm84dmdkga27aikl0q0gk4p8o.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&state=Nv0Fy3GH2girr0qQwm6c8f51rhQVHY&prompt=consent&access_type=offline
Enter the authorization code: 4/zQFaYruYLFkWQLg_4zvueMod7sG4xMjZmKRNBCigecdDxZsERNbNOeI
[youtube] _VNTaBO5K9I: Downloading webpage
[youtube] JK0K2eL7VqI: Downloading webpage
[youtube] vVfSKhIKe1s: Downloading webpage
[youtube] 0QAEhrTfFls: Downloading webpage
[youtube] -GC-Yzt7g90: Downloading webpage

C:\Users\Sheeba\Downloads\spotify>

**Comment by prithvi2226** [comment]
but there is one thing @Luiz6ustav0 @Luiz6ustav0 , the spotify playlist was created but there are no songs in it!still wondering what might be the case  :\

**Comment by Luiz6ustav0** [comment]
Did you watch music videos on youtube? Maybe the last couple videous you watched simply didn't have a match on spotify.

**Comment by jaredtewodros** [comment]
> but there is one thing @Luiz6ustav0 @Igorrubbo , the spotify playlist was created but there are no songs in it!still wondering what might be the case :\

did you ever figure out what the issue was with this bug? I have the same problem, but my YouTube playlist has music videos that exist in Spotify so I'm don't really sure where the error lives.

**Comment by pariharvivek92** [comment]
> > but there is one thing @Luiz6ustav0 @Igorrubbo , the spotify playlist was created but there are no songs in it!still wondering what might be the case :\
> 
> did you ever figure out what the issue was with this bug? I have the same problem, but my YouTube playlist has music videos that exist in Spotify so I'm don't really sure where the error lives.

Bro, I think Spotify can get access to read our database file.

**Comment by pariharvivek92** [comment]
> I was able to fix the problem! The solution was In the page that you get the OAuth token. You have to select the boxes when making the token. I wasn't selecting any and the program probaly wasn't getting the id becaues it wasn't allowed to
> ![Screenshot_2](https://user-images.githubusercontent.com/53878194/80752298-a5233e80-8b01-11ea-8806-0086b9f312e7.p

Is this gonna work because a playlist was created but empty
